package homework12;

import java.util.regex.Pattern;

public class Main {
    public static void main(String[] args) {
        Person person = new Person("Yuliia", "Malyk", "0955555555", "yul-mlk@gmail.com");
        person.info();
        Person person1 = new Person();
        person1.firstname = "Alina";
        person1.lastname = "Malyk";
        person1.phone = "0958888888";
        person1.email = "mlk.al@gmail.com";
        person1.info();
        System.out.println("----------");
        System.out.println(person.email);
        System.out.println(person.email.length());
        System.out.println(person.email.endsWith("ua"));
        System.out.println("------------------------");
        String email1 = "mal.yul555@bsmu.edu.ua";
        int a = email1.length();
        System.out.println(a);
        System.out.println(email1.endsWith("ua"));
        System.out.println(person1.email.endsWith("com"));
        System.out.println("------------------------");
        Course course = new Course("Java developer", "JavaScript developer", "Python developer", "C++ developer");
        System.out.println(course.name4.charAt(6));
        System.out.println(course.name3.indexOf("dev"));
        System.out.println(course.name2.concat(course.name1));
        System.out.println("----------");
        String s = course.name3 + course.name3;
        System.out.println(s);
        System.out.println(s.substring(7, 22));
        System.out.println(s.replace('P', 'S'));
        System.out.println("----------");
        System.out.println(course.name1.endsWith("developer"));
        System.out.println(course.name2.endsWith("developer"));
        System.out.println(course.name3.endsWith("developer"));
        System.out.println(course.name4.endsWith("developer"));
        System.out.println("----------");
        System.out.println(course.name1.startsWith("Java"));
        System.out.println(course.name2.startsWith("Java"));
        System.out.println(course.name3.startsWith("Java"));
        System.out.println(course.name4.startsWith("Java"));
        System.out.println("----------");
        Course course1 = new Course(course.name1, course.name2, course.name3, course.name4);
        System.out.println(course1.name4.toString());
        System.out.println(course1.toString());
        System.out.println("------------------------");
        Lecture lecture1 = new Lecture();
        String name1 = new String("Theme Introduction");
        String nameA1 = new String("Theme Introduction");
        String name2 = "Theme Variables";
        String nameA2 = "Theme Variables";
        String name3 = "Topic Methods";
        System.out.println(name1 == nameA1);
        System.out.println(name1.equals(nameA1));
        System.out.println(name2 == nameA2);
        System.out.println(name2.equals(nameA2));
        System.out.println("----------");
        System.out.println(name1.startsWith("Theme", 0));
        System.out.println(name2.startsWith("Theme", 0));
        System.out.println(name3.startsWith("Theme", 0));
        System.out.println("------------------------");
        String description1 = "Duration - 30 minutes";
        String description2 = "Duration - 60 minutes";
        String description3 = "   Duration - 90 minutes ";
        System.out.println(description1.regionMatches(11, description2, 11, 2));
        System.out.println(description1.regionMatches(0, description2, 0, 8));
        System.out.println(description2.regionMatches(13, description3, 16, 7));
        System.out.println(description3.trim());
        System.out.println("__________________");
        String text = name1 + " " + name2 + " " + name3;
        System.out.println(text);
        Pattern pattern = Pattern.compile("Theme");
        System.out.println(pattern.pattern());
        System.out.println(Pattern.matches("Theme", text));
        System.out.println(pattern.matcher(text).matches());
        System.out.println("________");
        String text1 = name3;
        System.out.println(text1);
        Pattern pattern1 = Pattern.compile("Topic Methods");
        System.out.println(pattern1.pattern());
        System.out.println(Pattern.matches("Topic Methods", text1));
        System.out.println(pattern1.matcher(text1).matches());
    }
}
