-- table structure (or schema)

-- MySQL Script generated by MySQL Workbench
-- -----------------------------------------------------
-- Schema mydb
-- Schema online_school_db
-- -----------------------------------------------------
-- Table `online_school_db`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_school_db`.`course` (
    `course_id` INT NOT NULL,
    `course_name` VARCHAR(45) NOT NULL,
    `lectures_number` INT NULL DEFAULT NULL,
    `teachers_number` INT NULL DEFAULT NULL,
    `students_number` INT NULL DEFAULT NULL,
    PRIMARY KEY (`course_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `online_school_db`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_school_db`.`teachers` (
    `teacher_id` INT NOT NULL,
    `teacher_name` VARCHAR(45) NOT NULL,
    `teacher_surname` VARCHAR(45) NOT NULL,
    `teacher_course_id` INT NOT NULL,
    `teacher_lectures_number` INT NULL DEFAULT NULL,
    PRIMARY KEY (`teacher_id`),
    INDEX `teacher_course_id` (`teacher_course_id` ASC) VISIBLE,
    CONSTRAINT `teacher_course_id`
    FOREIGN KEY (`teacher_course_id`)
    REFERENCES `online_school_db`.`course` (`course_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `online_school_db`.`lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_school_db`.`lecture` (
    `lecture_id` INT NOT NULL,
    `lecture_name` VARCHAR(45) NULL DEFAULT NULL,
    `lecture_course_id` INT NULL DEFAULT NULL,
    `lecture_teacher_id` INT NULL DEFAULT NULL,
    `add_mat_number` INT NULL DEFAULT NULL,
    `homework_number` INT NULL DEFAULT NULL,
    `lecture_date` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`lecture_id`),
    INDEX `lecture_course_id` (`lecture_course_id` ASC) VISIBLE,
    INDEX `lecture_teacher_id` (`lecture_teacher_id` ASC) VISIBLE,
    CONSTRAINT `lecture_course_id`
    FOREIGN KEY (`lecture_course_id`)
    REFERENCES `online_school_db`.`course` (`course_id`),
    CONSTRAINT `lecture_teacher_id`
    FOREIGN KEY (`lecture_teacher_id`)
    REFERENCES `online_school_db`.`teachers` (`teacher_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `online_school_db`.`additional_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_school_db`.`additional_materials` (
    `additional_materials_id` INT NOT NULL,
    `additional_materials_course_id` INT NOT NULL,
    `additional_materials_lect_id` INT NOT NULL,
    `URL` MEDIUMTEXT NULL DEFAULT NULL,
    `BOOK` MEDIUMTEXT NULL DEFAULT NULL,
    `VIDEO` MEDIUMTEXT NULL DEFAULT NULL,
    PRIMARY KEY (`additional_materials_id`),
    INDEX `additional_materials_course_id` (`additional_materials_course_id` ASC) VISIBLE,
    INDEX `additional_materials_lect_id` (`additional_materials_lect_id` ASC) VISIBLE,
    CONSTRAINT `additional_materials_lect_id`
    FOREIGN KEY (`additional_materials_lect_id`)
    REFERENCES `online_school_db`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `online_school_db`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_school_db`.`homework` (
    `homework_id` INT NOT NULL,
    `homework_course_id` INT NOT NULL,
    `homework_lecture_id` INT NOT NULL,
    `homework_points` INT NULL DEFAULT NULL,
    `homework_task` MEDIUMTEXT NULL DEFAULT NULL,
    PRIMARY KEY (`homework_id`),
    INDEX `homework_course_id_idx` (`homework_course_id` ASC) VISIBLE,
    INDEX `homework_lecture_id` (`homework_lecture_id` ASC) VISIBLE,
    CONSTRAINT `homework_lecture_id`
    FOREIGN KEY (`homework_lecture_id`)
    REFERENCES `online_school_db`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `online_school_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_school_db`.`students` (
    `student_id` INT NOT NULL,
    `student_name` VARCHAR(45) NOT NULL,
    `student_surname` VARCHAR(45) NOT NULL,
    `student_course_id` INT NOT NULL,
    `completed_hw` INT NULL DEFAULT NULL,
    `grade` INT NULL DEFAULT NULL,
    PRIMARY KEY (`student_id`),
    INDEX `student_course_id` (`student_course_id` ASC) VISIBLE,
    CONSTRAINT `student_course_id`
    FOREIGN KEY (`student_course_id`)
    REFERENCES `online_school_db`.`course` (`course_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/*
Table: additional_materials
Columns:
additional_materials_id int PK
additional_materials_course_id int
additional_materials_lect_id int
URL mediumtext
BOOK mediumtext
VIDEO mediumtext

Table: course
Columns:
course_id int PK
course_name varchar(45)
lectures_number int
teachers_number int
students_number int

Table: homework
Columns:
homework_id int PK
homework_course_id int
homework_lecture_id int
homework_points int
homework_task mediumtext

Table: lecture
Columns:
lecture_id int PK
lecture_name varchar(45)
lecture_course_id int
lecture_teacher_id int
add_mat_number int
homework_number int
lecture_date datetime

Table: students
Columns:
student_id int PK
student_name varchar(45)
student_surname varchar(45)
student_course_id int
completed_hw int
grade int

Table: teachers
Columns:
teacher_id int PK
teacher_name varchar(45)
teacher_surname varchar(45)
teacher_course_id int
teacher_lectures_number int
*/